import { FileSuggestion } from "./ai.service";

export interface AcceptedFileChange {
  filePath: string;
  changes: FileSuggestion[];
}

export interface PRResult {
  prUrl: string;
  prNumber: number;
  branchName: string;
}

interface CreatePROptions {
  repoUrl: string;
  githubToken: string;
  acceptedChanges: AcceptedFileChange[];
  prTitle: string;
}

// ─── URL parsing ─────────────────────────────────────────────────────────────

function parseGitHubUrl(repoUrl: string): { owner: string; repo: string } {
  const match = repoUrl.match(/github\.com[/:]([^/]+)\/([^/\s]+?)(?:\.git)?(?:[/#?]|$)/);
  if (!match) throw new Error("Only GitHub repositories are supported for PR creation");
  return { owner: match[1], repo: match[2] };
}

// ─── HTTP helpers ─────────────────────────────────────────────────────────────

async function ghFetch<T>(url: string, options: RequestInit): Promise<T> {
  const res = await fetch(url, options);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${res.status}: ${body}`);
  }
  return res.json() as Promise<T>;
}

function makeHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
    "User-Agent": "AI-Code-Reviewer",
  };
}

// ─── Change application ───────────────────────────────────────────────────────

function applyChange(
  fileContent: string,
  change: { lineNumber: number; currentCode: string; suggestedFix: string }
): string {
  // Method 1: exact string replacement
  if (change.currentCode && fileContent.includes(change.currentCode)) {
    return fileContent.replace(change.currentCode, change.suggestedFix);
  }

  // Method 2: line-based replacement with fuzzy matching near lineNumber
  const lines = fileContent.split("\n");
  const lineIdx = change.lineNumber - 1;
  const trimmedCurrent = change.currentCode.trim();
  const searchRadius = 5;
  const start = Math.max(0, lineIdx - searchRadius);
  const end = Math.min(lines.length - 1, lineIdx + searchRadius);

  for (let i = start; i <= end; i++) {
    if (lines[i].trim() === trimmedCurrent || lines[i].includes(trimmedCurrent)) {
      const indent = lines[i].match(/^(\s*)/)?.[1] ?? "";
      const fixLines = change.suggestedFix.split("\n").map((l) => indent + l.trimStart());
      lines.splice(i, 1, ...fixLines);
      return lines.join("\n");
    }
  }

  // No match found — return file unchanged to avoid corruption
  return fileContent;
}

// ─── PR body builder ──────────────────────────────────────────────────────────

function buildPRBody(acceptedChanges: AcceptedFileChange[]): string {
  const totalChanges = acceptedChanges.reduce((n, f) => n + f.changes.length, 0);
  const fileCount = acceptedChanges.length;

  const fileDetails = acceptedChanges
    .map((fc) => {
      const items = fc.changes
        .map((c) => `  - **${c.title}** (line ${c.lineNumber}) — \`${c.type}\``)
        .join("\n");
      return `### \`${fc.filePath}\`\n${items}`;
    })
    .join("\n\n");

  return [
    `## AI Code Review Fixes`,
    ``,
    `Applied **${totalChanges}** AI-suggested improvement${totalChanges !== 1 ? "s" : ""} across **${fileCount}** file${fileCount !== 1 ? "s" : ""}.`,
    ``,
    `---`,
    ``,
    fileDetails,
    ``,
    `---`,
    `*Generated by [AI Code Reviewer](https://github.com/Meetpp/Ai-Code-Reviewer)*`,
  ].join("\n");
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function createGitHubPR(options: CreatePROptions): Promise<PRResult> {
  const { repoUrl, githubToken, acceptedChanges, prTitle } = options;
  const { owner, repo } = parseGitHubUrl(repoUrl);

  const headers = makeHeaders(githubToken);
  const base = `https://api.github.com/repos/${owner}/${repo}`;

  const get = <T>(url: string) => ghFetch<T>(url, { headers });
  const post = <T>(url: string, body: unknown) =>
    ghFetch<T>(url, { method: "POST", headers, body: JSON.stringify(body) });
  const put = <T>(url: string, body: unknown) =>
    ghFetch<T>(url, { method: "PUT", headers, body: JSON.stringify(body) });

  // 1. Get default branch
  const repoInfo = await get<{ default_branch: string }>(base);
  const defaultBranch = repoInfo.default_branch;

  // 2. Get SHA of latest commit on default branch
  const refInfo = await get<{ object: { sha: string } }>(
    `${base}/git/ref/heads/${defaultBranch}`
  );
  const baseSha = refInfo.object.sha;

  // 3. Create new branch
  const branchName = `ai-review-fixes-${Date.now()}`;
  await post(`${base}/git/refs`, { ref: `refs/heads/${branchName}`, sha: baseSha });

  // 4. Apply changes to each file
  for (const fileChange of acceptedChanges) {
    const fileInfo = await get<{ content: string; sha: string }>(
      `${base}/contents/${fileChange.filePath}?ref=${branchName}`
    );

    // GitHub base64 includes newlines — strip them before decoding
    const currentContent = Buffer.from(
      fileInfo.content.replace(/\n/g, ""),
      "base64"
    ).toString("utf-8");

    // Apply changes from bottom to top to keep line numbers stable
    const sortedChanges = [...fileChange.changes].sort(
      (a, b) => b.lineNumber - a.lineNumber
    );
    let updatedContent = currentContent;
    for (const change of sortedChanges) {
      updatedContent = applyChange(updatedContent, change);
    }

    const commitMsg =
      fileChange.changes.length === 1
        ? `AI review: ${fileChange.changes[0].title}`
        : `AI review: apply ${fileChange.changes.length} suggestions to ${fileChange.filePath.split("/").pop()}`;

    await put(`${base}/contents/${fileChange.filePath}`, {
      message: commitMsg,
      content: Buffer.from(updatedContent).toString("base64"),
      sha: fileInfo.sha,
      branch: branchName,
    });
  }

  // 5. Create pull request
  const pr = await post<{ html_url: string; number: number }>(`${base}/pulls`, {
    title: prTitle || "AI Code Review Fixes",
    body: buildPRBody(acceptedChanges),
    head: branchName,
    base: defaultBranch,
  });

  return { prUrl: pr.html_url, prNumber: pr.number, branchName };
}
